import React from 'react';
import { Shield, Database, Eye, Lock, CheckCircle2 } from 'lucide-react';
import { Section, Bullet } from './Section';
import { PROBE_CATEGORIES } from './probe-categories';

export function TrustPolicySections() {
  return (
    <>
      {/* Methodology */}
      <Section icon={Eye} title="Our Testing Methodology">
        <p>
          Seclayer runs an automated black-box assessment from the outside in — the same vantage point a real
          attacker has. Every scan combines passive reconnaissance, active probing, and an authenticated deep crawl
          of your application surface, then maps the results to severity and concrete remediation.
        </p>
        <p className="mt-3">Each assessment exercises 70+ distinct checks across these areas:</p>
        <div className="grid sm:grid-cols-2 gap-2 mt-3">
          {PROBE_CATEGORIES.map((c) => (
            <div key={c} className="flex items-start gap-2 text-[11px]">
              <CheckCircle2 className="w-3.5 h-3.5 text-[#22c55e] shrink-0 mt-0.5" />
              <span>{c}</span>
            </div>
          ))}
        </div>
        <p className="mt-4 text-[11px] text-[#52525b]">
          Checks are aligned to the OWASP Top 10 and OWASP API Security Top 10. Findings include an evidence trail,
          a plain-English impact statement, and a tech-stack-specific code fix.
        </p>
      </Section>

      {/* Authorization / ethics */}
      <Section icon={Shield} title="Authorized Testing Only">
        <p>
          You may only scan systems you own or are explicitly authorized to test. Seclayer enforces SSRF protections
          and refuses targets that resolve to private, loopback, or link-local address ranges. By starting a scan you
          confirm you have permission to assess the target. Unauthorized scanning may violate computer-misuse laws and
          is grounds for account termination.
        </p>
      </Section>

      {/* Data handling */}
      <Section icon={Database} title="Data Handling &amp; Retention">
        <ul className="space-y-2.5">
          <Bullet><strong className="text-zinc-300">What we store:</strong> your account email, a hashed password
            (bcrypt — never plaintext), scan targets, scan results/findings, and API keys you generate.</Bullet>
          <Bullet><strong className="text-zinc-300">Where it lives:</strong> in a SQLite database on infrastructure
            under our control. Passwords are hashed; session tokens are signed JWTs.</Bullet>
          <Bullet><strong className="text-zinc-300">We do not sell your data.</strong> Scan results are yours. We do
            not share them with third parties except the AI provider used to generate your report narrative.</Bullet>
          <Bullet><strong className="text-zinc-300">AI processing:</strong> report summaries are generated by DeepSeek
            from your scan diagnostics. Target URLs and finding metadata are sent to produce the write-up; we do not
            send your credentials.</Bullet>
          <Bullet><strong className="text-zinc-300">Deletion:</strong> email <span className="text-[#22c55e]">privacy@seclayer.io</span> to
            request export or deletion of your account and associated scan data.</Bullet>
        </ul>
      </Section>

      {/* Account security */}
      <Section icon={Lock} title="Account &amp; Platform Security">
        <ul className="space-y-2.5">
          <Bullet>Passwords hashed with bcrypt; authentication via signed, expiring JWT session tokens.</Bullet>
          <Bullet>API keys are scoped per account, individually revocable, and never displayed again after creation.</Bullet>
          <Bullet>Rate limiting protects authentication and scan-initiation endpoints against abuse.</Bullet>
          <Bullet>All finding-suppression and remediation actions are recorded with a timestamped audit trail.</Bullet>
        </ul>
      </Section>
    </>
  );
}
