import { getClient, MODEL_PRO, REPORT_EFFORT } from './client.js';

/**
 * GitHub Auto-Fix — step 1: given a finding and a repo's file list, ask the
 * model which single file is the most plausible patch target. Returns null
 * (skip) if no DeepSeek key is configured or the model can't identify a
 * confident match — never guesses a file that wasn't actually in the list.
 */
export async function selectAutoFixFile(
  finding: { title: string; description: string; fix: string; codeFixExample?: string; category: string },
  filePaths: string[],
): Promise<{ targetFile: string } | null> {
  const client = getClient();
  if (!client) return null;

  try {
    const completion = await client.chat.completions.create({
      model: MODEL_PRO,
      messages: [
        {
          role: 'system',
          content: 'You are a senior security engineer choosing which file in a repository is the right place to patch a vulnerability finding. Respond as JSON only: {"targetFile": "<exact path copied from the provided list, or empty string if none is a confident fit>"}. Never invent a path that is not in the list.',
        },
        {
          role: 'user',
          content: `Finding:\nTitle: ${finding.title}\nCategory: ${finding.category}\nDescription: ${finding.description}\nRecommended fix: ${finding.fix}\n\nRepository file list:\n${filePaths.join('\n')}`,
        },
      ],
      response_format: { type: 'json_object' },
      reasoning_effort: REPORT_EFFORT,
      temperature: 0.1,
      max_tokens: 200,
    });
    const data = JSON.parse(completion.choices[0]?.message?.content?.trim() || '{}');
    const targetFile = typeof data.targetFile === 'string' ? data.targetFile.trim() : '';
    if (!targetFile || !filePaths.includes(targetFile)) return null;
    return { targetFile };
  } catch (err: any) {
    console.warn(`[AutoFix] File selection failed: ${err?.message || err}`);
    return null;
  }
}

/**
 * GitHub Auto-Fix — step 2: given the target file's current content, ask the
 * model to return the complete patched file. Returns null on any failure or
 * empty response — the caller must never open a PR with fabricated content.
 */
export async function generateAutoFixPatch(
  finding: { title: string; description: string; fix: string; codeFixExample?: string },
  targetFile: string,
  fileContent: string,
): Promise<{ newContent: string; prTitle: string; prBody: string } | null> {
  const client = getClient();
  if (!client) return null;

  try {
    const completion = await client.chat.completions.create({
      model: MODEL_PRO,
      messages: [
        {
          role: 'system',
          content: 'You are a senior security engineer writing a minimal, safe code patch for a confirmed vulnerability finding. You are given the full current content of one file. Return the COMPLETE new file content with the fix applied — preserve all unrelated existing code, change only what the fix requires. Respond as JSON only: {"newContent": "<entire file content after the fix>", "prTitle": "<short PR title>", "prBody": "<2-4 sentence PR description: the vulnerability and the fix>"}.',
        },
        {
          role: 'user',
          content: `Finding:\nTitle: ${finding.title}\nDescription: ${finding.description}\nRecommended fix: ${finding.fix}\n${finding.codeFixExample ? `Example fix pattern:\n${finding.codeFixExample}\n` : ''}\nFile: ${targetFile}\n\nCurrent file content:\n${fileContent}`,
        },
      ],
      response_format: { type: 'json_object' },
      reasoning_effort: REPORT_EFFORT,
      temperature: 0.2,
      max_tokens: 6000,
    });
    const data = JSON.parse(completion.choices[0]?.message?.content?.trim() || '{}');
    if (typeof data.newContent !== 'string' || !data.newContent.trim()) return null;
    return {
      newContent: data.newContent,
      prTitle: typeof data.prTitle === 'string' && data.prTitle.trim() ? data.prTitle.trim() : `Security fix: ${finding.title}`,
      prBody: typeof data.prBody === 'string' && data.prBody.trim() ? data.prBody.trim() : `Automated fix generated by Seclayer for: ${finding.title}`,
    };
  } catch (err: any) {
    console.warn(`[AutoFix] Patch generation failed: ${err?.message || err}`);
    return null;
  }
}
